spring:
  #profiles: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080

logging:
  level:
    com.sprint.mission.discodeit: debug
