spring:
  profiles:
    default: dev
  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql


springdoc:
  swagger-ui:
    enabled: true

discodeit:
  storage:
    type: local
    local:
      root-path: /path/to/storage